- hosts: nfsclient
  become: true
  roles:
    - criecm.nfs_client
  tasks:
    - name: Set rc.conf
      lineinfile:
        dest: /etc/rc.conf
        line: '{{ item.key }}="{{ item.value }}"'
        regexp: "^{{ item.key }}="
      with_items:
        - { key: autofs_enable, value: "YES" }
        - { key: nfscbd_enable, value: "YES" }

    - name: Push auto_master
      copy:
        dest: /etc/auto_master
        content: |+
          # $FreeBSD: releng/12.2/usr.sbin/autofs/auto_master 337749 2018-08-14 13:52:08Z trasz $
          #
          # Automounter master map, see auto_master(5) for details.
          #
          /mnt/net            -hosts          -nosuid,intr

    - name: Restart autofs services
      service:
        name: "{{ item.name }}"
        enabled: true
        state: "{{ item.state }}"
      with_items:
        - { name: automount, state: started }
        - { name: automountd, state: restarted }
        - { name: autounmountd, state: restarted }

    # - name: Install tree
    #   become: true
    #   pkgng:
    #     name: tree
    #     state: present

    - name: Get NFS dir
      # command: tree -L 5 /net/nfs.1.nctu.cs
      command: >
        ls -lh
        /mnt/net/nfs.1.nctu.cs/vol
        /mnt/net/nfs.1.nctu.cs/net/home
        /mnt/net/nfs.1.nctu.cs/net/data

      register: found_directories

    - name: List NFS dir
      debug:
        msg: "{{ found_directories }} "

    # - name: Includ nfs server var
    #   include_vars: "{{ inventory_dir }}/group_vars/nfs/vars.yml"

    # - name: Mount an NFS volume
    #   ansible.posix.mount:
    #     src: "nfs.1.nctu.cs:{{ nfs_shrae_dir }}"
    #     path: "{{ nfs_client_mnt_path }}"
    #     state: mounted
    #     fstype: nfs
