- hosts: nfsclient
  become: true
  # roles:
  #   - criecm.nfs_client
  tasks:
    # #因為沒有使用 ldap 服務,因此先把 nslcd 給關掉.
    - name: Set rc.conf
      lineinfile:
        dest: /etc/rc.conf
        line: '{{ item.key }}="{{ item.value }}"'
        regexp: "^{{ item.key }}="
      with_items:
        - { key: autofs_enable, value: "YES" }
        - { key: nslcd_enable, value: "NO" }
        - { key: nslcd_supervisor, value: "NO" }

    - name: Push autofs
      copy:
        dest: "{{ item.dest }}"
        content: "{{ item.content }}"
      with_items:
        - dest: /etc/auto_master
          content: |
            /net            -hosts          -nobrowse,nosuid,intr
            /data           /etc/auto.nfs   -intr,nfsv4,timeout=10,debug

        - dest: /etc/auto.nfs
          content: |
            home                            nfs.1.nctu.cs:/vol/home
            web_hosting                     nfs.1.nctu.cs:/vol/web_hosting

    - name: Restart autofs services
      service:
        name: "{{ item.name }}"
        enabled: true
        state: "{{ item.state }}"
      with_items:
        - { name: automount, state: started }
        - { name: automountd, state: restarted }
        - { name: autounmountd, state: restarted }
