---
- hosts: localhost
  tasks:
    - name: Generate private key
      openssl_privatekey:
        path: "{{ tls_private_dir }}/{{ openssl_name }}.key"

    - name: Generate CSR
      openssl_csr:
        path: "{{ tls_private_dir }}/{{ openssl_name }}.csr"
        privatekey_path: "{{ tls_private_dir }}/{{ openssl_name }}.key"
        common_name: "{{ openssl_name }}"
        # subject_alt_name: "DNS:{{ ansible_host }},DNS:{{ ansible_fqdn }}"

    - name: Pull CSR
      become: true
      fetch:
        src: "{{ tls_private_dir }}//{{ openssl_name }}.csr"
        dest: "{{ openssl_ownca_dir }}/{{ openssl_name }}.csr"
        flat: true

    - name: Sign CSR with CA key
      connection: local
      delegate_to: localhost
      openssl_certificate:
        path: "{{ openssl_ownca_dir }}/{{ openssl_name }}.crt"
        csr_path: "{{ openssl_ownca_dir }}/{{ openssl_name }}.csr"
        ownca_path: "{{ openssl_ownca_dir }}/root.crt"
        ownca_privatekey_path: "{{ openssl_ownca_dir }}/root.key"
        provider: ownca

    # - name: Push certificate
    #   become: true
    #   copy:
    #     src: "{{ openssl_ownca_dir }}/{{ openssl_name }}.crt"
    #     dest: "{{ {{ tls_private_dir }} }}/{{ openssl_name }}.crt"

    # - name: Push CA
    #   become: true
    #   copy:
    #     src: "{{ openssl_ownca_dir }}/root.crt"
    #     dest: "/etc/pki/ca-trust/source/anchors/root.pem"
