---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: rootca private key generator
      openssl_privatekey:
        path: "{{rca_openssl_privatekey_path}}"
        size: 2048

    - name: rootca cert request generator
      openssl_csr:
        path: "{{rca_openssl_csr_path}}"
        privatekey_path: "{{rca_openssl_privatekey_path}}"

    - name: rootca certificate generator
      openssl_certificate:
        provider: selfsigned
        path: "{{rca_openssl_certificate}}"
        privatekey_path: "{{rca_openssl_privatekey_path}}"
        csr_path: "{{rca_openssl_csr_path}}"

    - name: ldap private key generator
      openssl_privatekey:
        path: "{{ldap_openssl_privatekey_path}}"
        size: 2048

    - name: ldap cert request generator
      openssl_csr:
        path: "{{ldap_openssl_csr_path}}"
        privatekey_path: "{{ldap_openssl_privatekey_path}}"

    - name: ldap certificate generator
      openssl_certificate:
        provider: selfsigned
        path: "{{ldap_openssl_certificate}}"
        privatekey_path: "{{ldap_openssl_privatekey_path}}"
        csr_path: "{{ldap_openssl_csr_path}}"

- hosts: nctu-hw.vagrant.local
  gather_facts: false
  become: true
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /usr/local/etc/openldap/certificate
        state: directory
        mode: "0755"
    - copy:
        # src: "{{groups['all']['openssl_certificate']}}"
        src: ../plays/files/certificates/self-sign-server.crt
        dest: /usr/local/etc/openldap/certificate/server.crt
    - copy:
        src: ../plays/files/certificates/self-sign-server.key
        dest: /usr/local/etc/openldap/certificate/server.key

    - pkgng:
        name: openssl, perl5
        state: present

    - command: |
        cd /usr/local/etc/openldap/certificate && \
        c_rehash . && openssl verify -verbose -CApath . server.crt

    - import_role:
        name: criecm.openldap
      vars:
        openldap_schemas:
          - core
          - cosine
          - corba
          - inetorgperson
          - misc
          - nis
          - openldap
          - rfc2739
        openldap_bases:
          rootdn: cn=admin
          suffix: dc=1,dc=nctu,dc=cs
          # includes: [slapd.access]
          overlays:
            - dynlist
            - ppolicy
            - smbk5pwd
            - memberof
          indexes:
            - ["uid,uidNumber,gidNumber,memberUID", "pres,eq"]
          slave:
            rid: 675
            provider: ldaps://master.ldap.univ.fr:636
            binddn: cn=bind,dc=dn
            credentials: bindpw
            bindmethod: simple
