galaxy_info:
  role_name: mariadb
  author: Geoffroy Desvernay
  description: mariadb server instance(s) + DBs
  company: Ecole Centrale Marseille

  license: BSD

  min_ansible_version: 2.5

  platforms:
    - name: FreeBSD
      versions:
        - all

  galaxy_tags:
    - mariadb

dependencies: []
